#!/usr/bin/env python3
"""Generate results/INDEX.md: every artefact, what it holds, and who cites it.

The Phase 4 gate requires each number in the write-up to be traceable to a file
under results/. Sixty JSON files satisfy that in principle and defeat it in
practice, so this produces the map: what each artefact is, the headline figures
inside it, and which document quotes them.
"""

import json
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RES = REPO / "results"

CITED_BY = {
    "dataset_inventory.json": "docs/02-experiment-design.md §2",
    "batch_size_sweep/results.json": "docs/03-training.md §1",
    "compute_budget.json": "docs/03-training.md §2",
    "n_action_steps_comparison/results.json": "CLAUDE.md §3, docs/03-training.md §3",
    "teaching_cost_curve.json": "docs/04-findings.md §1, README",
    "task_difficulty.json": "docs/04-findings.md §5",
    "failure_analysis.json": "docs/04-findings.md §4",
}


def head(path: Path) -> str:
    """One line describing what is inside, read from the file itself."""
    try:
        d = json.loads(path.read_text())
    except Exception:
        return ""
    if "summary" in d:
        s = d["summary"]
        return f"{s['n_success']}/{s['n_episodes']} = {s['success_rate']*100:.1f}% success"
    if "points" in d:
        pts = ", ".join(f"K={p['K']}:{p['success_rate']*100:.1f}%" for p in d["points"])
        return pts
    if "tasks" in d:
        t = d["tasks"]
        return f"{len(t)} tasks, hardest {t[-1]['rate']*100:.0f}%, easiest {t[0]['rate']*100:.0f}%"
    if "runs" in d:
        ok = [r for r in d["runs"] if r.get("ok")]
        largest = max(r["batch_size"] for r in ok)
        return f"{len(d['runs'])} points, {len(ok)} fitted, largest ok batch {largest}"
    if "max_feasible_K" in d:
        return (f"{d['total_episodes']} episodes / {d['total_tasks']} tasks, "
                f"max feasible K = {d['max_feasible_K']}")
    if "scenarios" in d:
        return f"{d['plateau_samples_per_s']} samples/s plateau"
    if "arms" in d:
        return " vs ".join(f"{k.split('=')[1]}: {v['eval_ep_s']}s/ep" for k, v in d["arms"].items())
    if "failure_steps" in d:
        return (f"{d['failure_steps']['n']} failures, all at the "
                f"{d['failure_steps']['cap']}-step cap")
    return ""


def main() -> int:
    lines = [
        "# Results index",
        "",
        f"Generated by `src/analysis/make_index.py` on {datetime.now():%Y-%m-%d}.",
        "",
        "Every figure quoted in the documents traces back to one of these files.",
        "Evaluation runs are grouped; each holds per-episode records with seeds,",
        "success flags, episode lengths and the exact command that produced them.",
        "",
        "## Analysis artefacts",
        "",
        "| file | contents | cited by |",
        "|---|---|---|",
    ]
    for name, cite in CITED_BY.items():
        p = RES / name
        if p.exists():
            lines.append(f"| `results/{name}` | {head(p)} | {cite} |")

    groups = {
        "Teaching-cost runs (10 episodes/task)": sorted(RES.glob("stage2_k*_n10/results.json")),
        "Teaching-cost runs (5 episodes/task, superseded)": sorted(
            p for p in RES.glob("stage2_k*/results.json") if "_n10" not in p.parent.name),
        "K=0 reference": sorted(RES.glob("stage1_baseline*/results.json")),
        "Forgetting (evaluated on libero_spatial)": sorted(RES.glob("forgetting_*/results.json")),
        "Determinism gate": sorted(RES.glob("determinism_*/results.json")),
        "Pilots": sorted(RES.glob("pilot*/results.json")),
    }
    for title, paths in groups.items():
        if not paths:
            continue
        lines += ["", f"## {title}", "", "| run | result |", "|---|---|"]
        for p in paths:
            lines.append(f"| `results/{p.parent.name}/` | {head(p)} |")

    lines += ["", "## Timelines", ""]
    for log in sorted(RES.glob("*_milestones.log")):
        lines.append(f"- `results/{log.name}` — {sum(1 for _ in log.open())} milestone lines")

    out = RES / "INDEX.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
